0xsquid/squid-types

.github/worflows/code-validation.yml
=> feat: add basic workflow

package.json, tsconfig.json, yarn.lock
=> chore: fix building errors

package.json, src/path/index.ts
=> feat: add buckets type

src/quote/index.ts, src/routes/index.ts
=> feat: add guardrails types

package.json, src/routes/index.ts
- feat: add guardrail property to RouteRequestPopulated
WRITE_HERE
=> feat: add guardrail property

package.json, src/chains/index.ts
=> fix: revert rpc type

package.json, src/status/index.ts
- chore: add CCTP to status type
WRITE_HERE
=> chore: add CCTP to status type

package.json, src/chains/index.ts, src/dexes/index.ts
=> chore: release types package

package.json, src/chains/index.ts
* chore: add new blast chain
* chore: increment package version for release
WRITE_HERE
WRITE_HERE
=> Feat/add blast chain (#42)

package.json, src/dexes/index.ts
=> feat: add thruster dex on blast

package.json
=> chore: increment version

package.json
=> chore: increment version (#50)

package.json, src/dexes/index.ts
=> chore: add RamsesV3 DexName

package.json, src/dexes/index.ts
=> Merge develop > main

package.json
=> chore: increment package version

package.json, src/chains/index.ts, src/dexes/index.ts
- Release to main from Develop
WRITE_HERE
=> Release to main from Develop

package.json, src/dexes/index.ts
- Add dex name type for Wagmi V3
=> add dex name type for Wagmi V3

package.json, src/dexes/index.ts
* add dex name type for Wagmi V3
* increase version
---------
WRITE_HERE
WRITE_HERE
=> Release 0.1.73

package.json
* [squid-api#586] update @axelar-network/axelarjs-sdk to 0.16.1 (#62)
* feat: Trader Joe v2.1 types (#63)
* feat: Trader Joe v2.1 types
- Add Trader Joe v2.1 DexName and DexType
- Add binStep to ActionBaseData and SwapDetails type
* feat: DEX parity (#65)
* [squid-api#586] update @axelar-network/axelarjs-sdk to 0.16.1 (#62) (#64)
* chore: add Beamswap Saddle DexName
* chore: add Lynex V3 DexName
* fix: Pharaoh Solidly DexName
* chore: Nile/Ramses Solidly DexName
- Add back Ramses Solidly
- Add Nile Solidly (Linea)
* chore: add Ra, Pharaoh and Nile V3 DexNames
---------
* [squid-api#586] update @axelar-network/axelarjs-sdk to 0.16.1 (#62) (#64) (#67)
* chore: add Immutable types (#70)
* chore: add Immutable types
- ChainName and NetworkIdentifier
* chore: use IMMUTABLE_ZKEVM type
* chore: …
=> Dev to main (#93)

src/index.ts, src/rfq/index.ts
=> add RFQ types

package.json, src/path/index.ts, src/rfq/index.ts, src/routes/index.ts
=> rfq additions

package.json, src/fees/index.ts
=> add new fee types

package.json, src/routes/index.ts
=> add orderHash to route

package.json, src/squid/index.ts
=> add expiry for tx request

package.json, src/quote/index.ts, src/routes/index.ts
[TICKET](https://github.com/orgs/0xsquid/projects/3/views/31?pane=issue&itemId=78949391)
=> fix: remove onChainQuoting

package.json, src/rfq/index.ts
=> remove unused params

package.json, src/bridges/index.ts
[TICKET](https://github.com/orgs/0xsquid/projects/3?pane=issue&itemId=77949629)
=> feat: add immutable types

package.json, src/wrappers/index.ts
=> feat: add support for sky protocol wrapper

package.json, src/bridges/index.ts
=> update rfq provider

package.json, src/bridges/index.ts
=> capitalize provider

package.json, src/dexes/index.ts
https://docs.frax.finance/fraxswap/overview
=> add Fraxswap dex

package.json, src/squid/index.ts
Added expiryOffset property to OnChainExecutionData type
=> feat: add expiry offset type

package.json, src/chains/index.ts, src/compliance/index.ts
=> add berachain, bump package

package.json, src/chains/index.ts, src/fees/index.ts, src/routes/index.ts, src/squid/index.ts
=> feat: add support for Jito tip fees

package.json, src/chains/index.ts
- Add allora chain support
WRITE_HERE
=> chore: add allora chain

package.json, src/chains/index.ts, src/path/index.ts
- added XRPL chain related types
- fixed import path, no issue in this package but have issue when viewing the file from other application. using relative path solved the issue
=> add XRPL chain

package.json, src/chains/index.ts
feat: add new Saga chains to ChainName and NetworkIdentifier enums
WRITE_HERE
=> feat: add new Saga chains

package.json, src/chains/index.ts
chore: add BABYLON to ChainName and NetworkIdentifier enums
WRITE_HERE
=> feat: add BABYLON chain support

package.json, src/path/index.ts, src/rfq/index.ts, src/routes/index.ts, src/squid/index.ts
=> Fix type conflicts

package.json, src/chains/index.ts
=> add chain batch

package.json, src/rfq/index.ts
=> add `CoralMessageProvider` type

package.json, src/dexes/index.ts
=> add Swapr V3 DexName

package.json, src/dexes/index.ts
=> add Stellaswap V4

package.json, src/dexes/index.ts
=> Changed the version and added enum

package.json, src/fees/index.ts
=> add `receiver` to `FeeCost`
